### PR TITLE
release with multiple asi loader versions

### LINKED ISSUE #11: Multiple Release Archives
- base archive w/out ASI loader
- archive with Silent's ASI Loader 1.3
- archive with Ultimate ASI Loader
- archive with SDK (cleo.h and CLEO.lib + docs)

### PR DESCRIPTION
**Pull request by x87**
closes #11

### CODE REVIEW

**Comment by x87** [comment]
example build here https://github.com/cleolibrary/CLEO5/releases/tag/v5.0.0-alpha.54

**Comment by MiranDMC** [comment]
Readme file in both cases mentions ASI Loaded.
The "upd1" part in name "SA.CLEO_upd1+Silent_ASI_Loader.zip" will be different, right?

**Comment by x87** [comment]
> Readme file in both cases mentions ASI Loaded.

what do you mean by "both cases"?

**Comment by MiranDMC** [comment]
> what do you mean by "both cases"?

Inside both release packs.
https://github.com/cleolibrary/CLEO5/blob/v5.0.0-alpha.54/README.md?plain=1#L22

**Comment by MiranDMC** [comment]
It should be 'SA.CLEO_xxx_SDK.zip' instead of `SA.CLEO_xxx+SDK.zip`

Maybe simple `SA.CLEO_xxx.zip` instead of ``SA.CLEO_xxx_no_ASI_Loader.zip`

**Comment by x87** [comment]
It will be `_SDK` https://github.com/cleolibrary/CLEO5/pull/119/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R117
I wanted _no loader so people don't assume this is the default choice. This arhive is only for people who already have ASI loader. Otherwise I can imagine tons of questions like: "I downloaded CLEO.zip, why nothing happens when I run the game?"

**Comment by x87** [comment]
> cleo.li website also need an update with modern look.

in progress

**Comment by MiranDMC** [comment]
Maybe there should be no release without ASI loader at all? Is there any reason why UAL should not be default option?

**Comment by x87** [comment]
I dunno. I personally never used UAL in San Andreas (mainly because Silent's ASI loader was distributed with CLEO for years). We just give people options and they can chose whatever works for them.

No loader should be present in my opinion for those people who have ASI loader already (not necessarily SAL/UAL), so they just want to unzip the archive and not deal with extra libraries.

**Comment by x87** [comment]
>  Also adding a huge title to release section like "You need an asi loader to run CLEO" on top of the changelog

added an example [here](https://github.com/cleolibrary/CLEO5/releases/tag/v5.0.0-alpha.54), what do you think?

**Comment by x87** [comment]
> Also still think SDK should be last.

it will be last when it's generated with _ in the name, not +

**Comment by x87** [comment]
Updated download instructions again, giving more clarity on each choice.

**Comment by MiranDMC** [comment]
> Also adding a huge title to release section like "You need an asi loader to run CLEO" on top of the changelog

Does not matter how big text you place somewhere, there will be anyway (great?) percentage of regular users that will ignore it then complain. That's why "default" option should contain some kind of loader, be listed as first entry on list, and look like most basic, not complicated option to go.

**Pull request merged**
