### PR TITLE
Added load_fxt and unload_fxt opcodes

### PR DESCRIPTION
**Pull request by MiranDMC**

### CODE REVIEW

**Comment by MiranDMC** [comment]
Reworked

**Comment by MiranDMC** [comment]
Unload opcode is able to clear files loaded automatically from **cleo\cleo_text** location too.
After starting new game (new/load) **cleo_text** files are loaded again.
So, works as intended.

**Comment by x87** [comment]
Why do we need that? You can simply put your FXT in cleo_text

**Comment by MiranDMC** [comment]
> Why do we need that? You can simply put your FXT in cleo_text

You need it in case your mod provides more than one language. Then you are able to just load specified file. Plus all your mod related files can be placed in single directory.

I was thinking about opcodes like that before, but recent discussion about made me implement it.
https://discord.com/channels/357082905169625089/365620042731225088/1264343009189953718

**Review by x87 — APPROVED** [review]

**Pull request merged**
