### PR TITLE
New opcode set_result

### PR DESCRIPTION
**Pull request by MiranDMC**

### CODE REVIEW

**Comment by x87** [comment]
Use case?

**Comment by MiranDMC** [comment]
> Use case?

```
:FUNC
    (...)
    set_result true
cleo_return


:FUNC2
    (...)
    set_result 0@
cleo_return 1 0@


:FUNC3
    (...)
    not set_result 0@ // false if not zero
cleo_return 1 0@
```

`set_result true` is easier to remember and use than some opcodes like `is_game_australian`. It also can be used directly without constructing additional if-else statement.

**Comment by x87** [comment]
Aren't we going to implement cleo_return that does it in one opcode?
https://github.com/cleolibrary/CLEO4/pull/119

**Comment by MiranDMC** [comment]
Hmm I have to bring it back.

**Pull request closed without merging**
