### PR TITLE
Replaced default CLEO directory in start script opcodes.

### PR DESCRIPTION
**Pull request by MiranDMC**

### CODE REVIEW

**Comment by x87** [comment]
@MiranDMC 

https://github.com/cleolibrary/CLEO5/blob/9670d556b8a59f73432348746588ad8bcbb041c1/source/CScriptEngine.cpp#L719C28-L719C44

weakly_canonical returns an absolute path, so `ResolvePath("cleo") / fsPath` makes the path absolute.

**Comment by x87** [comment]
Can we update ResolvePath in such a way that it:

1) Resolves the absolute path:
  - if input path starts with a virtual prefix
     - resolve the prefix path and 
       - set `absolutePath` to prefix path + input path
  - if input path is absolute:
     - set `absolutePath` to input path
  - else if workdir has been set with 0A99:
     - resolve script workdir and
       - set `absolutePath` to workDir path + input path
  - else if customworkdir has been given:
     - resolve customworkdir and 
       - set `absolutePath` to customworkdir path + input path
  - else:
    - set `absolutePath` to game root path + input path

2. Before returning:
- if the absolute path starts with the usersettings directory:
  - return `absolutePath`
- else calculate a new path RELATIVE to the game directory (`relativePath`) and
  - if `relativePath` is not calculated:
    - throw an error
  - else:
    - return `relativePath`

**Comment by MiranDMC** [comment]
This is writing explicit ModLoader support, but embedded into fabric of whole internal CLEO logic.
There is difference between preparing file path before using it somewhere in hope ML picks it up with hooked APIs and resolving file paths for other purposes.

As proposed before whole path processing inside CLEO should be done without complicating it with ML peculiarities, then just translate resulting path to the ML standard just before using it.
However that solution is also weak as apparently ML is not consistent in it's working; some APIs work with absolute paths, other require relatives, returned results also vary.
Which mean every single place where path is send to some API it need to take in consideration how ML is handling it and how the path should be preprocessed.

CLEO5 was already rewritten to use absolute paths internally to avoid any ambiguities. Once resolved path is absolute and finite. Any further resolving causes no change.
Proper Mod Loader was implemented in branch:
https://github.com/cleolibrary/CLEO5/pull/143
Which was made by adding ML support to already existing void CLEO_ResolvePath and CLEO_ListDirectory exports.

**Comment by x87** [comment]
There is no new logic in the examples, it's just structured + tests cases are given. Which of them you think are wrong?

**Comment by x87** [comment]
What test case I provided is incorrect?

**Comment by MiranDMC** [comment]
They seems be logically ok, in matter of what you want to send to ML. As mentioned CLEO5 is intentionally not working on relative paths internally, so that logic can not be embedded in generic util function for resolving paths.

But... "logically" is not what ML is doing, as absolute/relative paths inconsistency was already observed.

**Comment by x87** [comment]
What functionality you expect to break if ResolvePath implementation changes to the proposed one?

**Comment by MiranDMC** [comment]
> What functionality you expect to break if ResolvePath implementation changes to the proposed one?

**resolve_filepath** opcode returning not resolved paths/mixed styles, cleo.log reporting ambiguous paths 
and potentially any operation in core or plugins that depended on fact resolved path is absolute.

**Comment by x87** [comment]
> resolve_filepath opcode returning not resolved paths/mixed styles, cleo.log reporting ambiguous paths

currently they return/report wrong paths assuming one location (CLEO) where in fact the physical location of the file is different (modloader). I think it is equally bad.

**Comment by MiranDMC** [comment]
> > resolve_filepath opcode returning not resolved paths/mixed styles, cleo.log reporting ambiguous paths
> 
> currently they return/report wrong paths assuming one location (CLEO) where in fact the physical location of the file is different (modloader). I think it is equally bad.

I think it is already solved in ML branch.
Resolving CLEO path is not so trivial, as each autostarted custom script believe it is located inside CLEO. To complicate things ML loads every cs file it find in any subdirectory of mod.

**Pull request closed without merging**
