### PR TITLE
Relax size limitations of 0a8d: READ_MEMORY

### PR DESCRIPTION
**Pull request by MiranDMC**
Allow reading memory into several consecutive variables, like `float pos[3]`

### CODE REVIEW

**Review by x87 — COMMENTED** [review]
you still copy to a 32-bit DWORD value. You need to get a pointer to script variable to copy directly to variables.

But you also have COPY_MEMORY which already allows it:

`COPY_MEMORY src (GET_VAR_POINTER 0@) 12`

**Comment by x87** [comment]
> copy_memory opcode requires getting variable pointer first.
yes, but it's just 1 extra line (for a very specific use case). No need to expand existing opcodes (and potentially introduce new issues), when the same can be achieved in other way

**Comment by MiranDMC** [comment]
Reason for that change is code I had:
```
float pos[3]
read_memory {address} ptr {size} 12 {vp} false
```
Seems weird that reading into float[3] needs different approach than into float.
There is also inconsistency, as similar **0A9D: read_from_file** opcode can do this.

**Comment by x87** [comment]
read_from_file is not a good example, as it should not have used var address as destination, but use var's value instead (later fixes with READ_BLOCK_FROM_FILE). Yes, it would have require extra GET_VAR_POINTER at the time, but allowed for more flexibility. Now we have READ_FROM_FILE and READ_BLOCK_FROM_FILE.

Now we introduce uncertainty here as well. What's going to happen here:

`READ_MEMORY 0xBEEFBEEF 32 false 33@` How is your check going to prevent going off the boundary of the local var space? With current implementation you can be certain, nothing escapes the variable you provide.

It also makes COPY_MEMORY less useful too. Why add multiple ways of achieving the same effect if existing opcodes already allow that?

**Comment by MiranDMC** [comment]
Yes, now **READ_MEMORY** and **COPY_MEMORY** would be exactly same duo as **READ_FROM_FILE** and **READ_BLOCK_FROM_FILE** are.

It would be possible to perform actual checks, but Sanny is compiling both `pos = ` and `pos[0] = ` as DL_LVAR instead of DT_LVAR_ARRAY.

**Comment by x87** [comment]
DT_LVAR_ARRAY requires a variable as index which does not exist in pos[0]

**Pull request closed without merging**
